openapi: 3.0.0
info:
    title: Api test
    version: 1.0.0
servers: [{ url: /v1 }]
tags:
    - name: administration
      description: Accès administrateur seulement
components:
    parameters:
        $ref: "parameters.yml"
    schemas:
        $ref: "schemas.yml"
paths: {}
